### ISSUE TITLE
OSX 10.10.3 Illegal instruction 4

### ISSUE THREAD

**Issue by JoshuaPettus** [asdfjkl/jerry#1]
Hi,  thank-you so much for making a, based on the screen-shot, great looking chess interface for OSX.  
Unfortunately I seem to be having difficulty getting it to run.  It quits with an Illegal instruction 4 upon launch. Here is the crashlog if that helps
https://www.dropbox.com/s/p9cqkj02tozdy52/jerry_crashlog.txt?dl=0

-----------
While I'm at it, it's fairly minor, but might I suggest that rather then use a .zip for distribution, that you use compressed .dmg images for osx?  It self verifies file integrity, is more professional, and it's what mac users generally expect.  You can either turn a folder into a compressed dmg image in Disk Utility, or use the command line:
hdiutil create -volname Jerry -srcfolder /path/to/jerry/folder -ov -format UDZO Jerry.dmg

Also gives you a place to put the license rather then buried in the .app bundle

**Comment by asdfjkl** [comment]
Thanks for your crash report. Concerning the .dmg, I'll consider that in the next release.

Concerning the crash, I have difficulties to reproduce that, since I currently have no machine with Yosemite available. Could you do me a favor and look whether there is any suspicious message in the system log? You can see the log by opening a terminal and running `open -a Console`...

**Comment by asdfjkl** [comment]
... and this is a complete shot in the dark (replace the packaged sip version), but you might want to give it a try:
https://www.dropbox.com/s/nba1jbqd3n8jsq5/Jerry.zip?dl=0

**Comment by JoshuaPettus** [comment]
I'm happy to help,  If you need any other info let me know.

**Comment by asdfjkl** [comment]
I created a new package. On a test machine where the same error occurred before, the new package worked. But I would very much appreciate if you could check whether it now works on your machine too. Here is a link https://www.dropbox.com/s/nba1jbqd3n8jsq5/Jerry.zip?dl=0
If it indeed fixes the issue, I'll make a new release on the main page...

**Comment by JoshuaPettus** [comment]
Hey, works great! Thanks!
