### ISSUE TITLE
Threshold in "Full Analysis" window

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#100]
Hi!
When we use "Full Analysis" feature, we always get default threshold i.e. 0.5 pawn material. It would be great if Jerry remembers our previous choice for example if I analysed a game with 1 pawn material threshold and after closing Jerry and reopening it next time, it should be 1 pawn instead of default 0.5 threshold. Just a feature suggestion!

**Comment by asdfjkl** [comment]
added in 23cbb7120123bc1940dad3b1898e4644908c2783 (game analysis settings) and in ca0cc6aba957de0ba605e8ae33ad3d9dc9e7a486 (settings for "New Game")
