### ISSUE TITLE
Can't play a game: new games start in "enter moves" despite what I choose

### ISSUE THREAD

**Issue by timrichardson** [asdfjkl/jerry#107]
I have 4.1.0 intstalled from the snap. 
I am a new user. 

I choose Game New... 
I choose Select Enemy: computer
I set computer strength (it doesn't matter, every option I have tried results in this problem)

I make a move ... and Stockfish does not respond..
Under the Mode menu, "Enter Moves" is ticked.
If I choose Play as White, Stockfish still does not move.
Choosing Play as Black rotates the board and allows me to move as Black, but Stockfish still does not respond.

**Comment by asdfjkl** [comment]
(fixed in 5497ddc17cd91e7102e6a98a6f7276d5dfb0bf6a ). Should do more testing before releasing snaps...

**Comment by asdfjkl** [comment]
(version 4.1.1)

**Comment by timrichardson** [comment]
thanks. new snap version upgraded!
