### ISSUE TITLE
Change the background color

### ISSUE THREAD

**Issue by ExtremeCoolDude** [asdfjkl/jerry#111]
Hello, I'm not a coder but wanted to adjust UI to my taste. I have a few questions, if you want me to open separate issues please let me know.

no. 1

 Is the background filled with lighter square colors ? is there a way to hardcode it without breaking things ? Thank you in advance. 

![image](https://user-images.githubusercontent.com/50034073/107748036-87496200-6d40-11eb-9c71-fbbd79c1cc21.png)

```
  if(colorStyle == STYLE_GREEN) {
            borderColor = BORDER_GREEN;
            coordinateColor = COORDINATE_COLOR_GREEN;
            darkSquareColor = DARK_SQUARE_GREEN;
            lightSquareColor = LIGHT_SQUARE_GREEN;
        }

```
I can't figure out which one is for background on `BoardStyle.java`  

```
public void updateCanvas() {

            GraphicsContext gc = this.getGraphicsContext2D();

            // fill background
            gc.beginPath();
            gc.setFill(Color.rgb(90, 59, 46));
            //gc.setFill(boardStyle.getLightSquareColor());
            gc.rect(0, 0, this.getWidth(), this.getHeight());
            gc.fill();

```
on  `ShowAppearanceBoard.java` I uncommented your commented part, so I expected background to fill with supplied rgb, but it was of the settings window : 
![image](https://user-images.githubusercontent.com/50034073/107750731-87e3f780-6d44-11eb-8f71-9857ca1bff2d.png)
 

no. 2 

On an completely unrelated note, when I run start.sh program starts without a problem, when I do java -jar {jerry.jar} it runs without a problem BUT when I create a desktop entry with no dashes etc (as per standard, proper permissions) no matter what I do I get "` Unable to access {jerry}.jar` " error message, would you have any idea as what would be causing it ? (Not sure if this issue  is of software or Linux)

no. 3 

I want to build the app with dark theme.  According to 
https://www.pixelduke.com/java-javafx-theme-jmetro/#Backgrounds

I tried to do on `App.java` on line 714 : 

```
 Style style = new Style();
        JMetro jMetro = new JMetro(style.DARK);
        jMetro.setScene(scene);
        jMetro.setautomaticallyColorPanes(true);
```
I keeping getting symbol not found error, please forgive me if this is a silly question, I don't know much coding.

**Comment by asdfjkl** [comment]
1.) Chessboard.java is the "main" board. Update updateCanvas() there. ShowAppearanceBoard and EnterPosBoard are for the graphics dialog and the dialog for entering a new position. You might update updateCanvas() there as well.
2.) check capitalization, it's JMetro jMetro = new JMetro(Style.DARK); not JMetro jMetro = new JMetro(**s**tyle.DARK);

**Comment by ExtremeCoolDude** [comment]
Thanks a lot ! Looks beautiful! 
![image](https://user-images.githubusercontent.com/50034073/108088663-d4ab3380-70a0-11eb-8e24-bc6c353246ff.png)

**Comment by asdfjkl** [comment]
looks nice indeed. Maybe I should add a dark mode in a future version...

**Comment by ExtremeCoolDude** [comment]
That'd be awesome! You could also publish Jerry(Dark version) executables only since its just a few lines modification.

Here's a somewhat messy patch incase someone wants a mod in the meantime.
https://gist.github.com/ExtremeCoolDude/d2c4f1f6fa12c47ee830dc82fd9fe213
