### ISSUE TITLE
Move highlighting on flipped board

### ISSUE THREAD

**Issue by KirkF** [asdfjkl/jerry#113]
Hello, system is Windows 10 running Jerry 4.1.1

When analysing games using engine with board flipped (from black's perspective) move highlighting is not flipped
![image](https://user-images.githubusercontent.com/7405734/109376746-bf01ef00-7894-11eb-8422-c4ac0acca63b.png)

Thanks for the software it's very useful

**Comment by asdfjkl** [comment]
fixed in a851a9df5c86382b322baf9e3d9c2b0871545eff
