### ISSUE TITLE
MultiPV not sent when restarting engine

### ISSUE THREAD

**Issue by KirkF** [asdfjkl/jerry#114]
System is Windows 10 running Jerry 4.1.1, connected to external Stockfish 13

After stopping engine analysis, when restarting does not display the correct number of lines

![image](https://user-images.githubusercontent.com/7405734/109397372-3b7fe680-7904-11eb-9b8e-703dc40dfba8.png)

Workaround requires clicking Lines dropdown again (e.g. clicking 3, then back to 4)

**Comment by asdfjkl** [comment]
fixed in c4efb1934b950791124bcc62eaa1e19f062bf7a2

**Comment by KirkF** [comment]
@asdfjkl I build master and tested and I get the same behavior. For what it's worth the idle engine thread patch seems to be working well as far as I can tell

**Comment by KirkF** [comment]
@asdfjkl What happens is the "Lines" dropdown only works if I change the value *while* the engine is running. It doesn't work properly if I change the value before I start the engine now

**Comment by asdfjkl** [comment]
should hopefully finally fixed in 62b940366e1bbc8ad0458bd7ef7936092d2bf9d1 and cec5d13ec04ef787c86ae6a2af0c5f69b805ecd3

**Comment by KirkF** [comment]
@asdfjkl so far it seems to be working how I expect, thanks. Although I don't understand https://github.com/asdfjkl/jerry/commit/62b940366e1bbc8ad0458bd7ef7936092d2bf9d1 and left a comment on that commit

**Comment by asdfjkl** [comment]
cf. ee9ece3805dc3260c58c1217b67a7796c7715d99 closing this for now.
