### ISSUE TITLE
PGN metadata persists in UI after New 

### ISSUE THREAD

**Issue by KirkF** [asdfjkl/jerry#115]
Jerry 4.1.1, Windows 10

After clicking "New" through tool bar or menu, PGN metadata is not cleared above the move box.
![image](https://user-images.githubusercontent.com/7405734/109594692-3fb52b00-7ae1-11eb-9806-6232d7bbec23.png)

Steps to reproduce: Load PGN that includes metadata (Players, Event, Date); Click New
Expected behavior: Label should be cleared when starting new game
Workaround: Can click edit button next to label and OK to clear label

Thanks

**Comment by asdfjkl** [comment]
(fixed in 748836060b82bdff2127a29afac69c1b1bcd0970 )
