### ISSUE TITLE
Weird program behaviour and engines that get removed reappeare

### ISSUE THREAD

**Issue by ScalieDan** [asdfjkl/jerry#119]
Hi,

There are some issues. I wanted to clean up the program but whenever I reinstalled it, everything was there again. Is there some shady things going on or why is this possible. Even when deleting the folder it picked positions or engines from didn't do it.

that issue came right after the other, I cannot remove an engine. It doesn't matter what I do here. Clear engine folder? nope. Reinstall after removing? nope. Simply clicking on remove and ok and quiting with the menu option does nothing. Closing after pressing ok, nothing. 

This is really weird...

**Comment by asdfjkl** [comment]
in Windows try deleting 

HKEY_CURRENT_USER/SOFTWARE/JavaSoft/Prefs/org.asdfjkl.jerryfx.gui./Game/Model

for Linux/snap delete ~/.java/.userPrefs/_!'8...

**Comment by ScalieDan** [comment]
> 
> 
> in Windows try deleting
> 
> HKEY_CURRENT_USER/SOFTWARE/JavaSoft/Prefs/org.asdfjkl.jerryfx.gui./Game/Model
> 
> for Linux/snap delete ~/.java/.userPrefs/_!'8...

Windows here

Can't find anything of that sort. No Jerryfx.gui or anything helping me to find it.
One folder looked promosing but nope... the fact that not only removing fails but resetting parameters too and it always saves the last position I entered.

i only need the setup .exe right?
Somnething seems broken here

**Comment by ScalieDan** [comment]
> 
> 
> > in Windows try deleting
> > HKEY_CURRENT_USER/SOFTWARE/JavaSoft/Prefs/org.asdfjkl.jerryfx.gui./Game/Model
> > for Linux/snap delete ~/.java/.userPrefs/_!'8...
> 
> Windows here
> 
> Can't find anything of that sort. No Jerryfx.gui or anything helping me to find it.
> One folder looked promosing but nope... the fact that not only removing fails but resetting parameters too and it always saves the last position I entered. Like nothing that I delete gets deleted.
> 
> i only need the setup .exe right?
> Somnething seems broken here

An update:

I deleted every file that had jerry in it, got the set up again and all is as it was before. I cannot delete it. Where is it saving what I did before? 

i think in the process I also deleted the file you mentioned. What is this XD.
No matter what I do, it recalls stuff it should not be able to. There is no data...

**Comment by asdfjkl** [comment]
please check again for the registry key (use Windows' regedit ) and delete the key. It must be there.

**Comment by TTorell** [comment]
Just would like to mention that reappearing engines was the topic of a pull request i sent in a while ago which was kindly accepted and merged into the master branch. But this seems to be a bigger problem.

**Comment by ScalieDan** [comment]
> Windows' regedit

Hi hi, got busy. Yeah I managed to reset everything using this. It really shouldn't be this hard to remove all this. Especially because you really can't get rid of it any other way. Kinda odd how remove and reset parameters just don't function (for me) and well, using the uninstall option provided in the setup couldn't delete itself properly x3.

Well thanks for helping!

**Comment by asdfjkl** [comment]
thanks for your patience. The next version will adress these issues:
- engine settings not correctly saved/restored (already fixed in current branch)
- delete all created registry keys during uninstall (InnoSetup)

**Comment by asdfjkl** [comment]
all created registry keys are removed during uninstall (Windows).
