### ISSUE TITLE
Opening Lichess' PGN problem

### ISSUE THREAD

**Issue by partik1** [asdfjkl/jerry#12]
Hey, version 3 of cherry seems to be much better than version 2, thank you!

So, I tried opening a Lichess' (www.lichess.org) PGN but I could only browse the moves until there is a comment. For example, check the following link:

http://en.lichess.org/xd2vSwf2/black#1

After the first move you've a comment which states the opening. The moves after that comment do not appear in Jerry's move list.

**Comment by asdfjkl** [comment]
seems to be a showstopper bug in the parser. thx, will look into it asap.

**Comment by asdfjkl** [comment]
fixed in commit https://github.com/asdfjkl/jerryv3/commit/a4bc5a80bdcb9daefc9c1db8c2d2f6934d95df47
