### ISSUE TITLE
Bookfile not found

### ISSUE THREAD

**Issue by TTorell** [asdfjkl/jerry#120]
Hi,
Updated my jerry-fork yesterday with your latest changes.
The program starts and seems to run OK, but there's an
exception at startup saying:
--- exec-maven-plugin:1.5.0:exec (default-cli) @ JerryFork ---
java.io.FileNotFoundException: /home/user/code/bookmaker/book.bin (No such file or directory)
und so weiter,
originating from GameModel line 121 and 122.
Are you experimenting with a larger opening book?

**Comment by asdfjkl** [comment]
Indeed, I've created an opening books with more stats (winning ratio, number of games played etc.). Still not finished though, so you can ignore that for now. Highly appreciate your contributions; just currently _very_ busy w/ work, so time on Jerry limited at the moment...

**Comment by asdfjkl** [comment]
latest version shipped with an opening book with stats
