### ISSUE TITLE
Sometimes highlights irrelevant squares as last move

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#121]
Hi,
Look at the move 50. Ke2, where highlighted squares are e7 and f6 instead of f3 and e2. Sometimes it works perfectly.
![jerry](https://user-images.githubusercontent.com/60097814/114572759-685e4200-9c95-11eb-8bf1-615baf21bb6b.PNG)

**Comment by asdfjkl** [comment]
thanks for reporting.

can you confirm that this always happens if the board is flipped, i.e. black is on the lower and white on the upper side? If so, this is already fixed in a851a9df5c86382b322baf9e3d9c2b0871545eff and the fix will be released together with the next version...

**Comment by manyapsycho** [comment]
Yes, true! This always happens if the board is flipped.
