### ISSUE TITLE
Java.dll Error

### ISSUE THREAD

**Issue by Batu-64** [asdfjkl/jerry#133]
Please help. When I run the program, it gives the warning in the picture! Java Runtime 8.33 64 bit and Java JDK 17 64 bit are installed on the PC. Operating system Windows 7 SP1 Ultimate 64 bit
![Java.dll.png](https://user-images.githubusercontent.com/46775864/180194245-e5d08d47-3626-493d-96ce-3a7fcfd8104d.png)

**Comment by asdfjkl** [comment]
It's hard for me to reproduce this bug. I've updated the windows package @https://github.com/asdfjkl/jerry/releases/tag/v4.2.1
Does this solve your issue?

**Comment by Batu-64** [comment]
Thank you., good works.
