### ISSUE TITLE
jerry won't start

### ISSUE THREAD

**Issue by adlertag** [asdfjkl/jerry#135]
oswald@pop-os:~$ jerry
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/oswald/snap/jerry/common
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1, mixed mode)
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/home/oswald/snap/jerry/common
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #39
  Current Serial #40

**Comment by asdfjkl** [comment]
OpenJDK 11 is too old and not supported. I recommend installing Jerry via Snap or switch to a newer JDK.
