### ISSUE TITLE
jfxchess server

### ISSUE THREAD

**Issue by ghost** [asdfjkl/jerry#143]

**Comment by asdfjkl** [comment]
to be honest, I am not sure what you are trying to say?!

**Comment by asdfjkl** [comment]
Sure, but JFXChess supports reading and writing PGN files since approx 10 years? In fact, I wrote about fast pgn parsing ( https://buildingjerry.wordpress.com/2020/02/29/towards-fast-pgn-parsing/ ) about 4 years ago...

**Comment by asdfjkl** [comment]
JFXChess is intended as a client-side (local) application, similiar to e.g. Acrobat Reader. PGN files are expected to be stored as PGN files in the file-system of the client (as an example like PDF files). There is no server to store PGN files, and I do not plan to host one.
