### ISSUE TITLE
Position repeated 3 times

### ISSUE THREAD

**Issue by scorici** [asdfjkl/jerry#18]
This is lacking, and the GUI doesn't stop the game if the position is repeated 3 times which would lead to a draw by silent "agreement".
This and 50 move rule will prevent the game to drag forever when playing against a stockfish level.
This can be either auto or manual claim of the repetition draw.
I prefer it auto.

**Comment by asdfjkl** [comment]
noted - it's on the todo list.

**Comment by asdfjkl** [comment]
this was added in 0285cdfd77b226f4ca786f328f592bf8e1dcea48

probably needs some testing...
