### ISSUE TITLE
50 move rule

### ISSUE THREAD

**Issue by scorici** [asdfjkl/jerry#19]
Without 50 move rule the game can drag on forever when playing against a stockfish level.
This is important when practicing K vs KBN endgame since it would require many moves to checkmate sometimes very close to 50 moves.

**Comment by asdfjkl** [comment]
noted. it's on the todo list.

**Comment by asdfjkl** [comment]
Detection of 50 moves rule was added in 376f71884c00e1d4fc31faa626b79ecb88017782
