### ISSUE TITLE
Can't move pieces in Enter Position 

### ISSUE THREAD

**Issue by scorici** [asdfjkl/jerry#21]
When setup/enter position is opened, there is no way of moving/dragging pieces on the board, which would simplify the click only setup of a position.

**Comment by asdfjkl** [comment]
I am not sure if I get 100% what you have in mind. Is there an existing chess program that could sever as an example for that functionality?

**Comment by scorici** [comment]
It's actually very simple. I open "Enter Position" and let's say I want to drag a piece from one square to another, it can't be done, I have to select the piece from the right panel and put it on the square I want it to be and delete the piece from the old square. With dragging that is not necessary, I can only click, hold and drop it on the square I want to move the piece on.
If I try dragging a piece it will only be replaced by the selected piece from the right panel.
I think ChessX does that pretty good, if you want an example...

**Comment by asdfjkl** [comment]
I see. I think this can be done. I'll look into it.

**Comment by asdfjkl** [comment]
bug in current dev with the following sequence:
1.) Enter Position
2.) Left Click on Board with a piece, release _on the the same square_
3.) Left Click on Board on the same sqare and drag
Piece should be displayed while dragging but it is not....

**Comment by asdfjkl** [comment]
(fixed in 708038230be6cad0ed0e49b068eefd3ebe676fe8). Some more testing; then this issue can be closed...?!

**Comment by asdfjkl** [comment]
Completely switched to drag'n'drop in eca20af6ce3667e6c60ad5b8acd7daa336fb77bd
