### ISSUE TITLE
Flip Board & New Game

### ISSUE THREAD

**Issue by scorici** [asdfjkl/jerry#23]
If you flip the board and have white up and black down, and start a new game against computer the board will look the same but the pieces are white on bottom and black up. If you try to move a white piece (up) with the mouse it will turn black (while dragging with the mouse) and viceversa.
But if you move the black king (down) it will transform into white queen and so on...
But that's not all !
For example: white is up and black is down, but it won't let me move any of the white pieces because it knows they are black even if it displays them as white so I tried to move on of the black pieces from bottom, for example d7-d5 but the move is not made, instead the move e2-e4 is made =)) this is the most funny bug I know :-)

**Comment by asdfjkl** [comment]
sorry about that. that's indeed a showstopper. Thanks for stopping.

**Comment by asdfjkl** [comment]
fixed in 9d2bf9e7d4572a3905af88fb382b69e0bf54daca 

Again thanks for reporting. Have some patience, I hope to release 3.0.5 with several bugfixes (including this one).
