### ISSUE TITLE
Problem building and running under windows

### ISSUE THREAD

**Issue by jwes44** [asdfjkl/jerry#3]
I was trying to build jerry under windows and had some problems.
1. I could find no documentation of the process. I guessed to rename setup.py_win to setup.py.
2. When I run build_win.bat, I get the error:
  C:\jerry-v.102>python setup.py py2exe --includes sip
  running py2exe
  error: Resource filename 'win_icon.ico' does not exist
3. When running build_win.bat a second time, the mkdir and xcopy commands give errors. You could remove the mkdir commands and add /I /D to the xcopy options and it will run without errors or prompts.
4. If I try to run jerry without compiling it, I get an error:
  C:\jerry-v.102>python jerry.py
Traceback (most recent call last):
  File "jerry.py", line 4, in <module>
    from gui.MovesEdit import MovesEdit
  File "C:\jerry-v.102\gui\MovesEdit.py", line 40
  SyntaxError: Non-ASCII character '\xe2' in file C:\jerry-v.102\gui\MovesEdit.py on line 40, but no
   encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Saving MovesEdit.py as utf-8 with BOM fixes that.

**Comment by jwes44** [comment]
Now that sourceforge is back up, I installed QtPy4. Now when I type python jerry,py, I get --
Traceback (most recent call last):
  File "jerry.py", line 4, in <module>
    from gui.MovesEdit import MovesEdit
  File "C:\Users\jwesley\jerry-v.102\gui\MovesEdit.py", line 4, in <module>
    from dialogs.DialogWithListView import DialogWithListView
ImportError: No module named dialogs.DialogWithListView

**Comment by asdfjkl** [comment]
Jerry is written in Python 3. Hence "building" is not really compilation, but just distribution for other systems. Hence if you want to try out the latest development version, there is really no need to execute the setup script.
Try the following:
- install python 3 and pyqt4
- git clone latest development build
- copy stockfish.exe to /engines folder
- open cmd.exe, go to the cloned folder and type 'python jerry.py'
hth. if there are errors, let me know. Note that I am currently changing _a lot_ (pgn handling) and the development versions are very unstable.

**Comment by asdfjkl** [comment]
due to the release of 2.0 I am closing this.
