### ISSUE TITLE
Adding stockfish 9

### ISSUE THREAD

**Issue by khoramshahi** [asdfjkl/jerry#30]
Hi,

I cannot add stockfish 9 as an engine in ubuntu 16.

**Comment by d-klein** [comment]
I finished a new version 3.1 recently, and I am currently testing the Windows binaries for any bugs. As soon as this is finished, I'll create a new debian/ubuntu package, including a recent stockfish. stay tuned...

**Comment by asdfjkl** [comment]
I am closing this, since I cannot reproduce this bug. I suggest that you directly install Jerry from the official debian package (sid), cf. https://packages.debian.org/sid/jerry or latest https://github.com/asdfjkl/jerry/releases/tag/v3.1.0 
Please reopen in case this does not resolve the issue.
