### ISSUE TITLE
Adding Hash Parameter in Engine Options

### ISSUE THREAD

**Issue by Spill-The-Tea** [asdfjkl/jerry#31]
At the moment, The Hash size cannot be adjusted through the engine parameters window. I've tried loading several different engines, including Komodo 9.02, Stockfish 10, SugRXPro1.4, and Ethereal 11.00, but none retrieve the option to adjust the Hash size. This would be really helpful.
I imagine this would require some tinkering with the dialog.engineoptions.cpp file.

**Comment by asdfjkl** [comment]
It's on the todo list!

**Comment by asdfjkl** [comment]
enabled to set the hash parameter in 410b442bb0fb01689b8bb3d2bd27d18af70e1b50

**Comment by Spill-The-Tea** [comment]
Thank you Dominic @asdfjkl !
