### ISSUE TITLE
How to build on Linux

### ISSUE THREAD

**Issue by rain0r** [asdfjkl/jerry#32]
How can I build Jerry myself on Linux?

I tried to pull some information on this from `build_ubuntu_64.sh` but it's just copying files and creating folders.

**Comment by asdfjkl** [comment]
I'll push the debian build files in the next days in the repo....

**Comment by Spill-The-Tea** [comment]
Hi Dominik @asdfjkl , 

I'm actually having a problem compiling this too.
Specifically :
main_window.cpp:426:58: error: address of overloaded function 'valueChanged' does not match required type

line 426 From main_window.cpp File:

connect(this->spinMultiPv, QOverload\<int>(**QSpinBox::valueChanged**), this->modeController, &ModeController::onMultiPVChanged);

I'm not exactly sure how to change this section to be able to compile it. Any insight would be helpful.
Cheers

**Comment by asdfjkl** [comment]
There are two signals valueChanged() which is why the overload is required. From my mind, there are three possibilities:

- You are using MSVC. Afaik, QOverload() is not supported in MSVC
- You are not passing (or it's not in the pro file?) CONFIG += c++14 (for this, C++14 is required)
- Replace this call with a manual cast (see below)

connect(spinbox, static_cast<void (QSpinBox::*)(int)>(&QSpinBox::valueChanged), this->modeController, &ModeController::onMultiPVChanged);

**Comment by Spill-The-Tea** [comment]
Interesting. I double checked the pro file and it defaulted to C++11.
I was able to modify it to the following, to become c++11 compatible:

connect(this->spinMultiPv, QOverload<int>::of(&QSpinBox::valueChanged), this->modeController, &ModeController::onMultiPVChanged);

But then I ran into other compiling problems, so I'll attempt compiling with c++14, and get back to you.

**Comment by asdfjkl** [comment]
hard to guess from here. Are you building the debian source package, or within QtCreator? If the later, one guess would be that your .pro file is not correct, i.e. that there are source-files missing, that source files are not listed in the correct order of dependency, or that libraries (such as +svg etc) are not correctly stated. Reference file is jerry3.pro.

**Comment by Spill-The-Tea** [comment]
I figured out the issue. I am actually building on mac OSx.
So, the problem was arising from various/resource_finder.cpp lines 9-17:

#ifdef __linux__
    QString appPath = "/usr/share/jerry/";
    return appPath;
#endif
#ifdef _WIN32
    QString appPath = QCoreApplication::applicationDirPath();
    return appPath.append(QDir::separator());
#endif

Slightly Altering this , allows Mac users to compile:

#ifdef __linux__
    QString appPath = "/usr/share/jerry/";
    return appPath;
#else
    QString appPath = QCoreApplication::applicationDirPath();
    return appPath.append(QDir::separator());
#endif

**Comment by asdfjkl** [comment]
currently preparing the 3.2 release; right now only bug-fix changes to the code. will merge this asap as soon as 3.2 is out.

**Comment by Atrament666** [comment]
Hi,
the directive #elseif in internalengine.cpp is not defined and causes the compilation to fail on linux, I suggest replacing it with #elif

Thanks

**Comment by asdfjkl** [comment]
#elseif fixed in ec24f96fbb8184489d8336bc5f431d817bd44605

If anyone encounters other build problems in Linux, please reopen a new issue.
