### ISSUE TITLE
Allow viewing of 1-5 PV lines from engine

### ISSUE THREAD

**Issue by Ivoz** [asdfjkl/jerry#33]
Hi, it would be nice nice to be able to see the 2nd or 3rd PV the engine is considering. Especially since there is a lot of white space in the engine lines textbox.

Maybe you could select how many PVs you'd like to see in the Options or Engines configuration box. Or as a small dropdown next to the OFF / ON Engine button. Cheers.

Very nice going otherwise for 3.1.

**Comment by asdfjkl** [comment]
Multi PV is planned for the next version

**Comment by asdfjkl** [comment]
multipv added in 5eaf30c80334ecc74eff6b52b29851715a93e216
