### ISSUE TITLE
Misplaced text in game data dialog

### ISSUE THREAD

**Issue by Ivoz** [asdfjkl/jerry#34]
Hopefully the picture is worth 1000 words.

![Jerry Game Data Dialog](https://i.imgur.com/8qhtWUr.png "Jerry Game Data Dialog")

**Comment by asdfjkl** [comment]
thanks for reporting. It's on the to-do list.

**Comment by asdfjkl** [comment]
fixed in 79cebe3c3a3ff0279e92cf62f17aba8506a52c13
