### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by Spill-The-Tea** [asdfjkl/jerry#42]
Hi Dominik,

Just wanted to say that I like what you did removing the ribbon bar. It looks much cleaner. 
In the near future, I'll send a pull request to update the osx project file to reflect the changes (i.e. removing all the ribbon/files). 

Also, I noticed that I happened to miss a forward slash in the previous pull request for icon paths in main_window.cpp, lines 67-68:

#ifdef __APPLE__
    QString resDir = QCoreApplication::applicationDirPath().append("../Resources"); 

It should instead be : 

#ifdef __APPLE__
    QString resDir = QString resDir = ResourceFinder::getPath().append("../Resources");

Darn details. Also, I'm not sure how they look on your end, but the icons are disproportionally large on mine. So I typically change main_window.cpp, line 324 to multiply by 0.75 (not 1.5), to look like this:

QSize iconSize = toolbar->iconSize() * this->devicePixelRatio() * 0.75;

Anywho, thanks.

**Comment by asdfjkl** [comment]
thx very much for your patches!

- will fix the #ifdef 
- concerning the #ifdef in piece_imgaes.cpp and main_window.cpp - are they really needed? Can't this be solved by just patching resource_finder.cpp?
- Icon sizes: There was a bug here: https://github.com/asdfjkl/jerry/commit/c55ee2b7b3e298f714119595df7c71945a2f2c29 this might already fix the issue - without outcommenting that line, icons were also extremly large on Windows with HighDPI mode. Do you happen to have a screenshot?

cheers

- Dominik

**Comment by Spill-The-Tea** [comment]
Okay, I took a look and played around with it again, and you are right about main_window.cpp
The second #ifdef is not needed and can be simplified to look like this (lines 704-717):

```
QAction* MainWindow::createAction(QString name, const QString &displayName, QSize &iconSize) {

    QString resDir = ResourceFinder::getPath();
    resDir.append("/res/icons/");
    resDir.append(name);
    resDir.append(".svg");
    QPixmap *iconPixmap = this->fromSvgToPixmap(iconSize, resDir);
    QAction *action = new QAction(QIcon(*iconPixmap), displayName);
    return action;
}

```

But it is absolutely needed in piece_images.cpp.
I also previously attempted to create a patch for all directory paths to be defined in resource_finder, so that it could be easily modified in the future, but my endeavors failed. That said, I agree that would be a better solution. As is, it works, but makes the code a little messy.

**Comment by asdfjkl** [comment]
managed to get ahold of an (ancient) Macbook. Currently setting things up, so I'll have the ability to debug myself. Would be highly appreciated if you could test a new build then...

**Comment by Spill-The-Tea** [comment]
Hi Dominik, Will do. If I don't see it right away when you make any changes, just let me know and I can test it on my end. 

I also created a pull request of minor fixes, (e.g. changed #elseif statements to #elif where applicable). Can you confirm it compiles without modification on your end (linux)? 

Lastly, I didn't want to include modifications to icon size (in the tool bar of both main app menu, and database menu) in the pull request, because I'm not certain how it looks on other computers, or other platforms. But can you check out, how reducing the size changes how things look on your end also? Something like this:

dialog_database.cpp, line 34:
`QSize iconSize = toolbar->iconSize() * this->devicePixelRatio()*0.75;`

main_window.cpp, line 323 or 324:
`QSize iconSize = toolbar->iconSize() * this->devicePixelRatio() * 0.75;`

**Comment by asdfjkl** [comment]
I've created several patches and a new build environment on macOS. You can try a new alpha build here. https://github.com/asdfjkl/jerry/releases/tag/Unsorted_Alphas
I will probably also close this issue soon, as there are too many things mixed by now within this thread.

The new layout (all engine output below board) is necessary to get more space on the right pane (#todo: opening book explorer), game progress graph etc. It's a no issue on other platforms, but vertical space is tight on macOS, especially on low res screens. Added some patches to get more vertical space.
