### ISSUE TITLE
AUR giving an error

### ISSUE THREAD

**Issue by qazip** [asdfjkl/jerry#49]
I am trying to install this from [AUR](https://aur.archlinux.org/packages/jerry/). Sadly, it's giving an error as the source link is 404ing.

> curl: (22) The requested URL returned error: 404 Not Found
> ==> ERROR: Failure while downloading https://github.com/asdfjkl/jerry/archive/v.306.tar.gz
>     Aborting...

**Comment by asdfjkl** [comment]
I do not package, provide or support AUR packages; hence I have no  clue what's going on there. I suggest you contact the package maintainer.
