### ISSUE TITLE
Jerry 3.2.1 does not run on Windows 7 SP1

### ISSUE THREAD

**Issue by esocrates** [asdfjkl/jerry#52]
I have installed the new version of Jerry 3.2.1 but it does not run on my Windows 7 SP1. When I try to run it a message of incompatibility is shown

**Comment by asdfjkl** [comment]
version 3.2.1 is 64 bit only. No 32bit support anymore, sorry. I suggest you update to Win7 64bit.

**Comment by asdfjkl** [comment]
will investigate in switching back to 32bit builds... stay tuned.

**Comment by asdfjkl** [comment]
https://github.com/asdfjkl/jerry/releases/download/v3.2.1/SetupJerryChess.exe is now a 32bit build. Feedback is appreciated.

**Comment by esocrates** [comment]
This new version of Jerry 3.2.1 32bit runs properly on  my Windows 7 . Thanks for your great work!!
