### ISSUE TITLE
Broaden the board

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#54]
If I try to broaden the board size, engine window below the board disappears. It would be great if windows can be floated, can be adjusted somewhere else.

**Comment by asdfjkl** [comment]
I'll keep this in mind, but no promises. it's always difficult to arrange ui-widgets in such way that the ui doesn't become a complete mess in one of the three platforms...

**Comment by asdfjkl** [comment]
1,) Floating is a "won't fix", as this requires really a fundamental design change. 2.) Engine window below board disappearing is fixed in v4; i.e. board can be pretty large right now.
