### ISSUE TITLE
Misleading mate annotation

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#56]
Hi!
After completing "Full Analysis" (with the engine, of course), scores given to each move show # (mate) but never show who is mating who.
For e.g.
![jerry bug](https://user-images.githubusercontent.com/60097814/76698198-0d3ed200-66c6-11ea-8881-50282c2210b1.png)
In the above image, if you come to Black's move no. 25 (as well as 27 and 29), { #10 } score is shown which means White is mating Black, but actually Black is mating White. { # -10 } would be more appropriate (adding minus sign in the score for Black).

**Comment by asdfjkl** [comment]
thanks for spotting. It seems that most programs use { - #10 } (i.e. like { - 1.243 }. I will fix this in the next version.

**Comment by manyapsycho** [comment]
Just for the sake of information, Scid Vs Pc is using a different approach. It uses some value above 300 in case of mate. In above case, it shows { - 327.60 }. I don't know how this no. is calculated. Probably 300 for the King in addition of other pieces.

**Comment by asdfjkl** [comment]
should be fixed in version 4. uses - sign.
