### ISSUE TITLE
No checkmate symbol in variation

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#58]
Hi!
Jerry doesn't show mate symbol in variation. Look at the screenshot.
![jerry2](https://user-images.githubusercontent.com/60097814/76858678-ef1bd200-687d-11ea-96d1-b17f3ff7e1d9.png)
Look at the Black's 25th move. 25... Rd1

**Comment by d-klein** [comment]
fixed in @2e589c3f089f

**Comment by asdfjkl** [comment]
fixed in @2e589c3f089f
