### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by MikeyBeez** [asdfjkl/jerry#59]
Thank you very much for writing this great program.  Is there a user guide or video describing features such as how to set the engine for a specific rating?   Cheers!

**Comment by asdfjkl** [comment]
Unfortunately there is no user guide or video. If you just want to play against a weaker Stockfish you can do so by Game -> New... and adjust the computer rating with the slider.

For other engines you can do so by setting engine parameters via UCI engine options, i.e. Edit -> Engines -> Add ... and then afterwards on "Edit Parameters"

The parameters or option name as well as the range values to adjust strength is not standardized and varies from engine to engine....

**Comment by MikeyBeez** [comment]
Thank you.
