### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Sky1101** [asdfjkl/jerry#62]
Thank you for providing this amazing piece of software for free. The following suggestions are minor and possibly arbitrary as the program is already perfect in my opinion. 

1) A fullscreen option would be nice so as to remove elements of the underlying desktop interface from view when focusing on the game.

2) Currently the program doesn't remember layouts ( I like to play with just the board in the middle of the screen and no other distractions ). It would also be nice to be able to bypass the popup window when the new game button is pressed - the program would remember my previous choice of initial game settings ( right now 'Select Enemy' always defaults to 'Just Enter Moves'). Another option that could be interesting under 'Choose your side' is 'Alternate'. So I press the 'New' button, a game starts immediately (without popup window), if I press the 'New' button again, a new game immediately starts, this time with me playing the other side.

Thank you again, your hard work is much appreciated. This is one of the cleanest chess GUIs I've come across and I've tried pretty much every GUI out there.

**Comment by asdfjkl** [comment]
Thanks for your suggestions. I am currently working on a version 4.0. Fullscreen should be possible, but is something for 4.1. Remembering layouts is already implemented. As for the popup windows, I'll consider this in future version. It requires some thought on how to exactly do this such that a user has easy access to the dialog in case he/she requires to change the options. Stay tuned :-)

**Comment by asdfjkl** [comment]
Fullscreen mode is implemented in 22f8e30eda505fa29bff047c0ffe3169a8004eca and will be available with 4.1.
