### ISSUE TITLE
Ability to modify font

### ISSUE THREAD

**Issue by Ivoz** [asdfjkl/jerry#9]
Hi there, with Jerry fullscreen on a 1920x1080 display, the font is quite small, and although I can read it, also quite hard to click on. It would also not be good for casting.

It would be nice to be able to set the size of the move display, possibly also the font?

Hopefully you can see all the empty space here:

![Jerry 1080p](https://i.imgur.com/Y4uzcSH.png)

Cheers, I'm liking this program so far.

**Comment by asdfjkl** [comment]
nice idea. will implement something in the rewrite (version 3.0=.

**Comment by asdfjkl** [comment]
https://github.com/asdfjkl/jerry/releases/tag/v.305 has support for High-Resolution displays. The font display will be automatically adjusted to the DPI ratio in Windows. Feedback is appreciated...

**Comment by asdfjkl** [comment]
Version 3.1 has cross platform support for High-Res displays, which is quite stable. Further methods of adjusting the font are currently not planned.

**Comment by Ivoz** [comment]
Hi, I tried version 3.1. Buttons work great. I still think it would be nice to have some options to increase increase font, maybe something like +125% and +150%

**Comment by asdfjkl** [comment]
will add a Font dialog in the next version

**Comment by asdfjkl** [comment]
custom font sizes are now possible. custom font families (i.e. Times New Roman instead of system default) will probably never happen, due to technical difficulties (support of Font Families in QTextBrowser HTML does not directly correspond to system available fonts)
