### ISSUE TITLE
No keyboard selection for moves' options window

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#90]
Hi, after analyzing a game, when we go through a mainline, where engines suggests its line, a window appears. We get two options, one is our line and one is suggested by engine. Here, keyboard doesn't work to choose a line, we must use mouse. Pretty awkward, isn't it?

**Comment by asdfjkl** [comment]
Do you run Linux? Currently trying to reproduce this, and the only bug I can find is that on linux, the pop-up dialog isn't focused. If I click with a mouse on the dialog, I can then selected the options via keys (arrow up/down & enter or arrow right)

**Comment by manyapsycho** [comment]
Ops, sorry, I didn't mention my O/S. Yes, I used it on Linux (Mint).

**Comment by asdfjkl** [comment]
(probably fixed in 99137780a6bd73f905dc217bd612862eb0845f6e )
