### ISSUE TITLE
Enhancement - Ribbon Hide/Show

### ISSUE THREAD

**Issue by manyapsycho** [asdfjkl/jerry#91]
Hi! Can we hide or show ribbon on top with double mouse click so that board size can be enlarged more after hiding ribbon? (something in the style of the big commercial role-model ;) )

**Comment by asdfjkl** [comment]
I'll look into it.

**Comment by asdfjkl** [comment]
(added in 844bbe9a6086af6723c67533852031a3e914aa2c )
